"""resource public_host

Revision ID: 0573d487a0cc
Revises: 36ac9803bb39
Create Date: 2026-07-01 17:07:19.150745

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0573d487a0cc'
down_revision: str | None = '36ac9803bb39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('public_host', postgresql.CITEXT(), nullable=True))
    op.create_unique_constraint(None, 'resources', ['public_host'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    op.drop_column('resources', 'public_host')
    # ### end Alembic commands ###
