"""gateway sessions and login states

Revision ID: 278129ba7514
Revises: 0573d487a0cc
Create Date: 2026-07-01 17:10:45.488863

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '278129ba7514'
down_revision: str | None = '0573d487a0cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_login_states',
    sa.Column('state_hash', sa.Text(), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=False),
    sa.Column('nonce', sa.Text(), nullable=False),
    sa.Column('return_url', sa.Text(), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_table('gateway_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idp_session_id', sa.UUID(), nullable=False),
    sa.Column('cookie_secret_hash', sa.Text(), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idp_session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gateway_sessions_user_id', 'gateway_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gateway_sessions_user_id', table_name='gateway_sessions')
    op.drop_table('gateway_sessions')
    op.drop_table('gateway_login_states')
    # ### end Alembic commands ###
