"""session stepup challenge

Revision ID: 36ac9803bb39
Revises: b66be004150c
Create Date: 2026-07-01 16:23:07.481837

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '36ac9803bb39'
down_revision: str | None = 'b66be004150c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('stepup_challenge', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'stepup_challenge')
    # ### end Alembic commands ###
