"""login flow recovery_used

Revision ID: b66be004150c
Revises: 63f071395d1e
Create Date: 2026-07-01 16:17:12.491570

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b66be004150c'
down_revision: str | None = '63f071395d1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_flows', sa.Column('recovery_used', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_flows', 'recovery_used')
    # ### end Alembic commands ###
